---
galaxy_info:
  author: rcbops
  description: Install libvirt and run a virtual machine
  company: Rackspace
  license: Apache2
  min_ansible_version: 2.0.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  categories:
    - cloud
    - python
    - development
    - openstack
