

Networking:
  bond_interfaces:
  - name: bond0
    mtu: 1500
    nics:
    - name: ens2
      mtu: 1500
  host:
    dns_search: rpc-cp-c.net
    gateway: 10.30.10.1
    interface: bond0
    nameservers: 10.184.227.134
    address: 10.30.10.81
    netmask: 255.255.255.0
  mgmt:
    interface: ens3
    address: 10.30.20.13
    netmask: 255.255.255.0
    range: 10.30.20.20,10.30.20.253
  template: interfaces-active-passive-ironic.j2
role: logging
